# Generated by Django 5.1.2 on 2024-10-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdirectory', '0002_rename_clients_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsfeed',
            name='imageurl',
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
