# Generated by Django 5.1.2 on 2024-10-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdirectory', '0004_client_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='building',
            field=models.IntegerField(),
        ),
    ]
