# Generated by Django 5.1.2 on 2024-10-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdirectory', '0007_values'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Values',
        ),
    ]
