# Generated by Django 5.1.2 on 2024-10-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdirectory', '0008_delete_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisibleby', models.IntegerField(default=12)),
                ('data_interval', models.IntegerField(default=10000)),
            ],
        ),
    ]
