# Generated by Django 5.1.2 on 2024-10-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdirectory', '0009_configuration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
