# Generated by Django 5.1.2 on 2024-10-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdirectory', '0010_delete_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
